name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Copy files to Production location
        run: sudo cp -r ${GITHUB_WORKSPACE} /var/www/links.blakemiller.ca
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./    
      - uses: actions/checkout@v2
