name: Deploy site

on:
  push:
    branches: ["public"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ${{ env.BUILD_PATH }}/src

  deploy:
    name: Deploy to Remote Server
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: src

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H 137.184.174.226 >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/github-actions-key" src/ blake@137.184.174.226:/var/www/links.blakemiller.ca/
