name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Copy files to Production location
        run: sudo cp -r ${GITHUB_WORKSPACE} /var/www/links.blakemiller.ca
